Fix Welcome Cog for dpy2
Injabie3/lui-cogs-v3 pull request #2
Opened 2022-03-26 05:29 UTC by KaguneAstra

Fixes minor issue with __setup__.py and fixes minor issue with async message send.

2022-03-26 05:36 UTC, Injabie3 requested changes

2022-03-26 05:36 UTC, Injabie3 commented on welcome/welcome.py
> +            await ctx.send(f"{name} not in list of greetings")
Can you put this in a separate PR and merge this into master, since this is not directly related to dpy2?

2022-04-11 07:13 UTC, Injabie3 commented
Any updates here?

2022-04-23 21:55 UTC, KaguneAstra commented
Fix has been removed and another PR has been opened with the minor change

2022-04-26 05:16 UTC, Injabie3 approved these changes

2022-04-26 05:23 UTC, merged